name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [created]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    
  deploy:
    if: github.event_name == 'release' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 8.0.x
      - name: Set package version
        id: set-version
        run: |
          CURRENT_DATE=$(date +'%Y%m%d')
          BUILD_NUMBER=$GITHUB_RUN_NUMBER
          # Package version can be more detailed
          PACKAGE_VERSION="2.0.${CURRENT_DATE}.${BUILD_NUMBER}"
          # Assembly version needs to be simpler (major.minor.build.revision)
          ASSEMBLY_VERSION="2.0.0.${BUILD_NUMBER}"
          echo "Generated Package Version: $PACKAGE_VERSION"
          echo "Generated Assembly Version: $ASSEMBLY_VERSION"
          echo "PACKAGE_VERSION=$PACKAGE_VERSION" >> $GITHUB_ENV
          echo "ASSEMBLY_VERSION=$ASSEMBLY_VERSION" >> $GITHUB_ENV
      - name: Build and Pack with version
        run: dotnet build --configuration Release /p:Version=$PACKAGE_VERSION /p:PackageVersion=$PACKAGE_VERSION /p:AssemblyVersion=$ASSEMBLY_VERSION /p:FileVersion=$ASSEMBLY_VERSION
      - name: Publish to NuGet
        run: dotnet nuget push "**/*.nupkg" --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
